# Makefile for "Wayne's Little DSA Library"
# (DSA == Data Structures and Algorithms)
# Feel free to change, modify, or burn these sources, but if you modify them
# please don't distribute your changes without a clear indication that you've done so.
# If you think your change is spiffy, send it to me and maybe I'll include it
# 
# Wayne Hayes, whayes@uci.edu (previously wayne@cs.toronto.edu)

# The below variables should be set by a parent process
#CC=$(LIBWAYNE_HOME)/bin/wgcc
CC=../bin/wgcc -ggdb

#% : %.c
#	$(CC) -c $(CFLAGS) %.c
#	wf77 -o % %.o

OBJS=sim_anneal.o circ_buf.o hash.o raw_hashmap.o aloha.o htree-test.o avltree-test.o bintree-test.o combin.o graph-sanity.o tinygraph-sanity.o graph-weighted.o integrate-friction.o integrator-order.o integrators.o linked-list-test.o normStat.o queue.o revlines.o sparse-set-sanity.o set-sanity.o stats.o stream48.o test_SSetDict.o test_llfile.o uncmind.o x_mouse.o x_random.o
