// This software is part of github.com/waynebhayes/libwayne, and is Copyright(C) Wayne B. Hayes 2025, under the GNU LGPL 3.0
// (GNU Lesser General Public License, version 3, 2007), a copy of which is contained at the top of the repo.
#ifndef UTILS_H
#define UTILS_H
#include <vector>
#include <map>
#include <ostream>
#include <unordered_map>
#include "templateUtils.cpp"
#include <stdint.h>

using namespace std;

//low-level functions (**oblivious** to SANA or network alignment) but that are useful in multiple places.

//folder where any part of the codebase can save autogenerated files
extern const string AUTOGENEREATED_FILES_FOLDER;
extern const char *SANAversion;

typedef uint16_t ushort;
typedef uint32_t uint;

bool myNan(double x);

double randDouble();
int randInt(int low, int high);
int randMod(int n);
void randomShuffle(vector<uint>& v);

string extractDecimals(double value, int count);
string toLowerCase(const string& s);
vector<string> nonEmptySplit(const string& s, char c); //keeps only non-empty strings

double vectorMean(const vector<double>& v);
void normalizeWeights(vector<double>& weights);

void printTable(const vector<vector<string>>& table, int colSeparation, ostream& stream);

string currentDateTime();

string exec(string cmd);
string execWithoutPrintingErr(string cmd);
void execPrintOutput(string cmd);

#endif /* UTILS_H */
