CC=gcc$(GCC_VER)
CXX=g++$(GXX_VER) -std=c++11
all: mt19937 threads

mt19937: MTGenerator.hpp test-mt.c mt19937.cpp mt19937.h
	$(CC) -c test-mt.c
	$(CXX) -std=c++11 -c mt19937.cpp
	$(CXX) -o mt19937 test-mt.o mt19937.o

threads: test-threads.c thread-sets.h FutureAsync.hpp FutureAsync.cpp mt19937.cpp
	$(CC) -I../include -c test-threads.c
	$(CXX) -I../include -std=c++11 -c FutureAsync.cpp
	$(CXX) -o threads test-threads.o FutureAsync.o mt19937.cpp -lpthread

clean:
	/bin/rm -f *.o mt19937 threads
